export const GET_LANDING_SUCCESS = "GET_LANDING_SUCCESS";
export const GET_LANDING_FAILURE = "GET_LANDING_FAILURE";

export const GET_LOGIN_SUCCESS = "GET_LOGIN_SUCCESS";
export const GET_LOGIN_FAILURE = "GET_LOGIN_FAILURE";

export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";
export const POST_LOGIN_FAILURE = "POST_LOGIN_FAILURE";

export const POST_DECISION_SUCCESS = "POST_DECISION_SUCCESS";
export const POST_DECISION_FAILURE = "POST_DECISION_FAILURE";

export const CLEAR_DECISION = "CLEAR_DECISION";

export const SAVE_QUESTION_ANSWER = "SAVE_QUESTION_ANSWER";
export const CLEAR_QUESTION_ANSWER = "CLEAR_QUESTION_ANSWER";

export const VALIDATION_ERROR = "VALIDATION_ERROR";

export const BAD_REQUEST = "BAD_REQUEST";
